### ISSUE TITLE
Bug: BOT has been moved

### ISSUE THREAD

**Issue by NicolaescuCatalin** [TeeSeal/Musen#1]
After the BOT has been manually moved by admins, it cannot receive commands

![SmartSelect_20230308_122407_Discord](https://user-images.githubusercontent.com/51510298/223693139-5608bade-a79d-4c88-87e5-7e2c018a24c5.jpg)

**Comment by TeeSeal** [comment]
Tat lucreaza 💯 po fixil

**Comment by NicolaescuCatalin** [comment]
maladeț
